language: python
sudo: required
python:
    - 3.5
    - 3.6-dev

install:
    - pip install --upgrade setuptools
    - pip install codecov
    - pip install -Ur requirements-dev.txt
    - python setup.py develop

script:
    make cov
after_success:
    codecov

env:
    matrix:
        - PYTHONASYNCIODEBUG=x
        - PYTHONASYNCIODEBUG=
